name: CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore
      - name: Get Cache Key
        id: get-cache-key
        run: |
          dotnet list ./test/ToDoApp.Web.Tests package --format json
          dotnet list ./test/ToDoApp.Web.Tests package --format json | jq -c '.projects'
          echo "cache-key=$(dotnet list ./test/ToDoApp.Web.Tests package --format json |
            jq -c '.projects[] | .frameworks[] | .topLevelPackages[] | select(.id | startswith("Testcontainers"))' |
            sha256sum)"
          echo "cache-key=$(dotnet list ./test/ToDoApp.Web.Tests package --format json |
            jq -c '.projects[] | .frameworks[] | .topLevelPackages[] | select(.id | startswith("Testcontainers"))' |
            sha256sum)" >> $GITHUB_OUTPUT
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.5
        with:
          key: ${{ steps.get-cache-key.outputs.cache-key }}
      - run: dotnet test
